-- Campus Clinic Inventory and Patient Records System
-- Database Schema for Supabase (PostgreSQL)

-- --------------------------------------------------------
-- Table structure for table "medicines"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "medicines" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255) NOT NULL,
  "category" varchar(100) DEFAULT 'General',
  "stock" integer NOT NULL DEFAULT 0,
  "expirationDate" date DEFAULT NULL,
  "dateAdded" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- Dumping data for table "medicines"
INSERT INTO "medicines" ("name", "category", "stock", "expirationDate") VALUES
('Paracetamol 500mg', 'Painkiller', 150, '2026-12-31'),
('Amoxicillin 250mg', 'Antibiotic', 85, '2026-06-15'),
('Cetirizine 10mg', 'Antihistamine', 120, '2026-09-20'),
('Ibuprofen 400mg', 'Painkiller', 60, '2026-11-10'),
('Mefenamic Acid', 'Analgesic', 45, '2026-08-05')
ON CONFLICT DO NOTHING;

-- --------------------------------------------------------
-- Table structure for table "patients"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "patients" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "fullname" varchar(255) NOT NULL,
  "age" integer DEFAULT NULL,
  "gender" varchar(20) DEFAULT NULL,
  "department" varchar(100) DEFAULT NULL,
  "complaint" text DEFAULT NULL,
  "diagnosis" text DEFAULT NULL,
  "dateVisit" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- Dumping data for table "patients"
INSERT INTO "patients" ("fullname", "age", "gender", "department", "complaint", "diagnosis") VALUES
('John Student Doe', 20, 'Male', 'Engineering Department', 'Headache and minor fever', 'General Fatigue'),
('Jane Smith', 19, 'Female', 'Information Technology Department', 'Stomach ache', 'Hyperacidity'),
('Michael Brown', 21, 'Male', 'Education Department', 'Sprained ankle during sports', 'Minor Sprain')
ON CONFLICT DO NOTHING;

-- --------------------------------------------------------
-- Table structure for table "prescriptions"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "prescriptions" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patientId" bigint NOT NULL,
  "medicineId" bigint NOT NULL,
  "quantity" integer NOT NULL,
  "issuedAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY ("patientId") REFERENCES "patients"("id") ON DELETE CASCADE,
  FOREIGN KEY ("medicineId") REFERENCES "medicines"("id") ON DELETE CASCADE
);

-- Dumping data for table "prescriptions"
INSERT INTO "prescriptions" ("patientId", "medicineId", "quantity") VALUES
(1, 1, 2),
(2, 5, 1),
(3, 4, 3)
ON CONFLICT DO NOTHING;

-- --------------------------------------------------------
-- Table structure for table "users"
-- --------------------------------------------------------
CREATE TABLE IF NOT EXISTS "users" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(100) NOT NULL UNIQUE,
  "password" varchar(100) NOT NULL,
  "email" varchar(255) NOT NULL UNIQUE,
  "fullname" varchar(255) DEFAULT NULL,
  "role" varchar(50) DEFAULT 'Staff',
  "login_otp" varchar(10) DEFAULT NULL,
  "otp_expires_at" timestamp with time zone DEFAULT NULL,
  "createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP
);

-- Dumping data for table "users"
INSERT INTO "users" ("username", "password", "email", "fullname", "role") VALUES
('admin', 'admin123', 'leonelmontebon18@gmail.com', 'Primary Campus Nurse', 'Admin')
ON CONFLICT ("username") DO NOTHING;
